homepage:
    pattern:  /
    defaults: { _controller: PtrackerAuthBundle:Default:index }

register:
    pattern:  /register
    defaults: { _controller: PtrackerAuthBundle:Default:register }
    
login:
    pattern:  /login
    defaults: { _controller: PtrackerAuthBundle:Default:login }
    
activate:
    pattern:  /activate/{username}/{salt}
    defaults: { _controller: PtrackerAuthBundle:Default:activate }

login_check:
    pattern:  /login_check