parameters:
#    ptracker_auth.example.class: Ptracker\AuthBundle\Example

services:
#    ptracker_auth.example:
#        class: %ptracker_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
