PtrackerTasksBundle:
    resource: "@PtrackerTasksBundle/Resources/config/routing.yml"
    prefix:   /

PtrackerAuthBundle:
    resource: "@PtrackerAuthBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
